name: "Practice Workflow"
on: 
    push:
        branches:
            - main
jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: "Yoooo" 
              run: echo "Hello The Workflow is sucessfully Executed!"